### ISSUE TITLE
Coffeescript wrong code-suggestion

### ISSUE THREAD

**Issue by J-F-B-M** [codecombat/codecombat#2371] opened 2015-02-22 00:40 UTC
I wrote `atta` (half of attack) in the code-editor, than got distracted by something else. After a short time, the parser detected that he doesn't now `atta` and suggested `this.attack`. Correct would be `@attack`

**Comment by AnirudhGP** [comment] 2015-02-23 10:12
Hi this is my first bug. How can i fix this ?

**Comment by popey456963** [comment] 2015-02-23 11:36
First step would be to test it in production to make sure the bug actually exists.  Then you should go check whether being away for a short while actually matters.  If it does, unsure, if it doesn't, you'll need to make a change to the corrector.

**Comment by J-F-B-M** [comment] 2015-02-23 12:03
Failed to click on the comment button, sorry...

**Comment by AnirudhGP** [comment] 2015-02-23 16:57
Which code editor is this ? How do i open it?

**Comment by J-F-B-M** [comment] 2015-02-23 22:06
The ingame code-editor. The one where you press Run or Submit after you finished coding.

**Comment by divyanshu013** [comment] 2015-03-02 18:54
I'm unable to reproduce this bug, can you help @J-F-B-M ?

**Comment by nwinter** [comment] 2016-05-22 18:30
Closing until we can reproduce.

**Closed by nwinter** 2016-05-22 18:30 UTC
Labels: bug, good-for-newbies
