### ISSUE TITLE
Premature celebration - win notice when losing

### ISSUE THREAD

**Issue by buddyatkins** [codecombat/codecombat#1543] opened 2014-09-11 12:12 UTC
"I occasionally run across a bug where, when first opening the level while playing against an opponent, it gives me a message that I've won even though I've lost" - David Beckly

![image](https://cloud.githubusercontent.com/assets/8581710/4233571/ec493dac-39ac-11e4-8aef-2aeff5e35f51.png)

**Comment by nwinter** [comment] 2015-02-11 23:55
Duplicate of #1133; gonna just ignore it, as it's in the old-style levels.

**Closed by nwinter** 2015-02-11 23:55 UTC
Labels: bug, duplicate
