### ISSUE TITLE
Python compilation error

### ISSUE THREAD

**Issue by txomon** [codecombat/codecombat#2731] opened 2015-05-03 23:17 UTC
This has been driving me nuts for 2 hours, and I am now giving up. I have tried to make it work, but there where several errors spawning. Uploading two of them

```python
# This level is intended to be for advanced players. The solution should be pretty complex with a lot of moving parts. It might also be a bit of a gear check unless you use "creative" methods.
# You need to make your way to the first trial (Oasis of Marr) killing enemies along the way. When you reach it, pick all the mushrooms to trigger the trial to begin. If you survive the onslaught, make your way to the next Oasis for the second trial, then the Temple. When all trials are complete you will have to face the final boss. Good luck!
# HINT: Glasses with a high visual range help tremendously on this level so buy the best you can get.
# HINT: the unit 'type' for the oasis guardians is 'oasis-guardian'

def filter_by_distance(items, meters):
    return [item for item in items if self.distanceTo(item) < meters]

def filter_by_type(items, item_type):
    return [item for item in items if item.type == item_type]

def length(items):
    list_length = 0
    for item in items:
        list_length += 1
    return list_length

def order_by_distance(items):
    sorted_items = []
    while(length(items)>0):
        item = self.findNearest(items)
        sorted_items.append(item)
        items.remove(item)
    return sorted_items

def electrocute(target):
    return
    if self.canElectrocute(target):
        self.electrocute(target)

def bash(enemy):
    return

def attack(enemy):
    self.attack(enemy)

def kill(enemy):
    while enemy.health > 0:
        distance = self.distanceTo(enemy)
        electrocute(enemy)
        # Bash has 3m range
        bash(enemy)
        attack(enemy)

def kill_by_custom_order(enemies, enemy_types):
    for enemy_type in enemy_types:
        targeted_enemies = filter_by_type(enemies, enemy_type)
        if not targeted_enemies:
            continue
        for enemy in targeted_enemies:
            kill(enemy)

def kill_by_order(enemies):
    enemy_types = ["fangrider", "shaman", "thrower", "scout", "munchkin"]
    kill_by_custom_order(enemies, enemy_types)

def kill_by_distance(enemies):
# HERE ERROR
    self.say(len(enemies)) 
    enemies = order_by_distance(enemies)
    for enemy in enemies:
        kill(enemy)

enemies = self.findEnemies()
enemies = filter_by_distance(enemies, 50)
#kill_by_order(enemies)
kill_by_distance(enemies)
self.say("Finished")
```

![screenshot from 2015-05-04 01-14-32](https://cloud.githubusercontent.com/assets/228250/7447404/f1fbc682-f1fa-11e4-83ed-f94e6a7c8432.png)

The second error I haven't been able neither to trace it down.... 
![screenshot from 2015-05-04 00-40-41](https://cloud.githubusercontent.com/assets/228250/7447412/3985fc66-f1fb-11e4-95b6-70842f22f982.png)

Tested it with:
```python
a = [ 1,2,3,4]
b = a[:]
print(b)
```
in https://rawgit.com/differentmatt/filbert/master/test/interactive.html

**Comment by txomon** [comment] 2015-05-03 23:23
Also, if instead of len() you use my function length(), it will say() 0...

**Comment by txomon** [comment] 2015-05-04 20:43
For some reason, if I execute the kill_by_order, the list won't be null, but if I execute the kill_by_distance it will be null

**Comment by Codehimn** [comment] 2015-05-14 12:02
Buenas, supongo que ya lo habrás resuelto , pero aunque no tiene sentido si le cambias el nombre a la variable (argumento) , funciona.

(por cierto , te recomiendo que uses las banderas para este mundo )

def kill_by_distance(enemies2):
# HERE NO MORE ERROR
    self.say(len(enemies2))
    enemies = order_by_distance(enemies2)
    for enemy in enemies:
        kill(enemy)

**Comment by txomon** [comment] 2015-05-14 12:05
Just in case, @Codehimn is saying that there is a name collision, and that renaming enemy to enemy2 works.

**Comment by UltCombo** [comment] 2015-11-29 21:16
Seems like a dupe of differentmatt/filbert#70 / #2880.

**Comment by nwinter** [comment] 2016-05-22 19:14
Should be fixed with @basicer's new Esper interpreter.

**Closed by nwinter** 2016-05-22 19:14 UTC
