### ISSUE TITLE
Broken Wall in Oasis

### ISSUE THREAD

**Issue by monotkate** [codecombat/codecombat#2608] opened 2015-03-31 18:39 UTC
In the Oasis level in the desert you can move left as long as there is an enemy through the wall and hang out until they're all gone.  Fun, but probably not right. :D

![image](https://cloud.githubusercontent.com/assets/11742296/6926364/c3a0938c-d7b3-11e4-85dd-059ff9f29955.png)

**Comment by Imperadeiro98** [comment] 2015-03-31 19:26
Duplicate of #2609.

**Closed by Imperadeiro98** 2015-03-31 19:26 UTC
Labels: duplicate
