### ISSUE TITLE
Problems with ladder games

### ISSUE THREAD

**Issue by ebirkenes** [codecombat/codecombat#1830] opened 2014-12-02 19:33 UTC
I'm seeing some strange behaviour in the ladder games.
1. When I play a game using the Play as Humans button, it's never added to my matches. (Against a human opponent and I click submit of course.)
2. When I click on the 'Defeat the ogres' link to see what went wrong in a match that I lost, I always win. I've must have tried this over 20 times today and yesterday, and won ALL of them. 

That can't be right..

**Comment by yaur** [comment] 2015-01-29 22:45
Returning 404s or bogus json objects in response to level.session or thang.type causes the simulation software to lock up.  So whatever is going on here is more subtle than simple network failures.

**Comment by yaur** [comment] 2015-02-03 02:48
More data.  Rerunning the bad match ups in the simulator (tested in chrome and IE) gives correct/reasonable results.

**Comment by nwinter** [comment] 2015-02-03 17:21
So it's possible that the bad matchups are being caused by a bad simulation client being unable to load certain code properly and incorrectly erroring out those players, and we only see intermittent bad matches due to this because many correct simulation clients are also simulating?

**Comment by sotonin** [comment] 2015-02-12 02:47
I've noticed that when i lose a match and click it to see it. I typically always win the match.

**Comment by nwinter** [comment] 2015-02-12 05:05
I've hooked it up so that we are tracking who simulates which matches, so if you see a bad match, hover over it and look for patterns in who is simulating it using which browser, etc.

![screenshot 2015-02-11 21 04 28](https://cloud.githubusercontent.com/assets/99704/6162094/b9b748e0-b231-11e4-8830-333a9435add7.png)

**Comment by nwinter** [comment] 2015-02-12 19:38
I found and fixed two sources of possible error so far:

1. The random seeds were not taking into account the number of times each session had been submitted for real-time playback in the Simulator, whereas when playing, the random seeds would take that into account–but differently depending on which side you were playing, so even two players watching the same match between themselves would see a different random seed. I have taken the submission count out of the random seeds for now; it was only really interesting for sync PVP, anyway, so I'll fix it when we get that going again.

2. chess was right–the match playbacks were remembering each players' flag history, but the Simulator wasn't taking those into account. Most players didn't use flags, but some of them did, and this would cause discrepancies. Now the Simulator also remembers the last flags placed by each player. This isn't perfect, because the flags can be updated independently of a code resubmission, but that should be an even smaller problem similar to when players submit again and you can't see the code they had at the time your match was played with them, which we can fix by a better architecture (like in #651).

Let's keep our eyes out for more sources of discrepancy, but I'm guessing things will be a lot more accurate now.

**Comment by nwinter** [comment] 2015-02-13 00:38
Seen a couple more, so I guess something is still up. I'll add more analytics.

**Comment by nwinter** [comment] 2015-02-13 18:16
We now show the random seed that was used to simulate the match when you hover over the row, so let's see whether the random seed is the same if you ever see two matches against the same player in quick succession and they disagree. Or, if the match disagrees, see if the random seed it spits out in the JS console when replaying the match is the same as the one in the tooltip on the match result row.

**Comment by nwinter** [comment] 2018-01-25 20:40
Haven't seen any problems with this for a while; closing until we find more.

**Closed by nwinter** 2018-01-25 20:40 UTC
Labels: bug
