### ISSUE TITLE
Level Editor Tab-out

### ISSUE THREAD

**Issue by purenickery** [codecombat/codecombat#2192] opened 2015-01-31 23:16 UTC
If you tab out of the level editor and return later, sometimes the level turns all black and has scrolling issues

**Comment by popey456963** [comment] 2015-02-02 11:24
What operating system are you using, browser, version of browser, rough time until it goes black?

**Comment by divyanshu013** [comment] 2015-02-24 15:05
I'm unable to reproduce this bug. @purenickery could you provide some more information?

**Comment by nwinter** [comment] 2015-02-27 19:18
Closing until we can reproduce; I'm guessing this might be related to running out of graphics memory or something like this.

**Closed by nwinter** 2015-02-27 19:18 UTC
Labels: bug
