### ISSUE TITLE
 Error: Cannot find module '../../bower_components/treema/treema-utils.js'

### ISSUE THREAD

**Issue by gkua** [codecombat/codecombat#4475] opened 2017-10-03 20:10 UTC
Whats wrong with it?

**Comment by sderickson** [comment] 2017-10-16 03:07
Can you provide more details? When is this happening? Is there more to the trace? You might need to run `npm install` or `bower install` to make sure everything is set up.

**Comment by sderickson** [comment] 2017-10-16 03:11
Duplicate of #4443

**Closed by sderickson** 2017-10-16 03:11 UTC
