### ISSUE TITLE
canCast auto correct loses if

### ISSUE THREAD

**Issue by nemoyatpeace** [codecombat/codecombat#2042] opened 2015-01-03 06:27 UTC
When I type `if canc` I canCast is highlighted so I hit enter to activate the auto complete and it is replaced with `self.canCast('drain-life',target)`

Would be nice if it was replaced with `if self.canCast('drain-life',target)`.

**Comment by nwinter** [comment] 2015-01-03 06:33
@differentmatt what would cause the autocomplete to replace the `if` there?

**Comment by nemoyatpeace** [comment] 2015-01-03 06:35
By the way, if I do `if self.c` and hit the auto correct it replaces perfectly.

**Comment by nixel2007** [comment] 2015-01-03 11:40
Neh, noticed it either at coffeescript and the 'else' keyword. I thought parser search the (), and if it can't find it, it replaces whole string. But it doesn't correlate with 'if self.c' situation.

**Comment by nemoyatpeace** [comment] 2015-01-03 12:36
Rather than replacing whole line, would make more sense for it to replace backwards to a space.

**Comment by nixel2007** [comment] 2015-01-03 21:09
Or (, "&", "||" and other special symbols.

**Comment by differentmatt** [comment] 2015-01-06 20:29
Looks like a bug in our [autocomplete](https://github.com/differentmatt/zatanna).  I'll look into it.

**Comment by differentmatt** [comment] 2015-01-06 21:54
Caused by an autocomplete insertion bug: https://github.com/differentmatt/zatanna/commit/7d659853bfdf653cad0f45f2ea1ecdec99e6eea6

Should be fixed after next production deploy.

**Closed by differentmatt** 2015-01-06 21:54 UTC
Labels: bug
