### ISSUE TITLE
Coffeescript error detection problem

### ISSUE THREAD

**Issue by Darredevil** [codecombat/codecombat#1391] opened 2014-07-27 19:58 UTC
I noticed that when you play a level in coffeescript and have an error in the code, the level always points the error at the first character regardless of the actual location:
"Syntax error on line 1, column 1 ..."

**Comment by nwinter** [comment] 2016-05-22 17:35
Duplicate of #1310 which is fixed.

**Closed by nwinter** 2016-05-22 17:35 UTC
Labels: bug
