### ISSUE TITLE
local install in level3 failed

### ISSUE THREAD

**Issue by coollerjack** [codecombat/codecombat#3284] opened 2015-12-27 11:23 UTC

**Comment by UltCombo** [comment] 2015-12-27 23:38
Dupe of #3281

Although the engine is open source and free, the level contents have rights reserved (so CodeCombat can sell subscriptions, after all). Only a handful of levels are included in the public DB dump so you can work on the engine and test it.

**Comment by coollerjack** [comment] 2015-12-28 01:14
thanks for your anwser! @UltCombo

**Closed** 2015-12-28 14:22 UTC
