### ISSUE TITLE
A button to navigate from codecombat.com/play to codecombat.com

### ISSUE THREAD

**Issue by divyanshu013** [codecombat/codecombat#2251] opened 2015-02-06 17:03 UTC
One thing I noticed is that from www.codecombat.com/play there is no button to return to www.codecombat.com. It might look good at the top right corner titled "Home"

![issue_home](https://cloud.githubusercontent.com/assets/6682655/6083646/1f7e49e8-ae50-11e4-8809-2b7bfbb0b079.png)

**Comment by Imperadeiro98** [comment] 2015-02-06 20:02
Duplicate of #2044 (point 1).

**Closed by Imperadeiro98** 2015-02-06 20:02 UTC
