### ISSUE TITLE
Bug with Kithgard Gates level - tmp2[tmp3] is not a function

### ISSUE THREAD

**Issue by ekazda** [codecombat/codecombat#2862] opened 2015-06-26 13:58 UTC
This is using Coffeescript

![capture](https://cloud.githubusercontent.com/assets/1107804/8378804/e9f4112e-1be9-11e5-95c2-542d62a0b8a1.PNG)

**Comment by UltCombo** [comment] 2015-06-27 22:37
Which boots were you wearing?
If you were wearing anything other than `Simple boots`, then your hero won't have a `moveDown` method.

What is really odd to me is that it looks like the `@moveDown()` part is inside the "header" (dashed border area) meaning it cannot be edited, but when I open the level here, there is no "header" part -- that is, the entire code is editable for me.

**Comment by Vlevo** [comment] 2015-06-27 23:41
As UltCombo suggests, you either have *moveDirection* **OR** *moveXY* not both...

That isn't the error I'd expect to get for that problem, but when you mix coco with your coffescript :smile: you get some pretty bizarre errors and that *is* the error I get when the move command and my boots are mismatched.

**Comment by nwinter** [comment] 2015-06-30 02:49
Ah, let's keep it open until I fix that error message. (Again–I could have sworn I had it, but maybe I didn't get all the cases. Anyway, it's really easy to reproduce, so it's silly that I thought I fixed it.)

**Comment by nwinter** [comment] 2016-05-22 19:38
Should be fixed with @basicer's new Esper interpreter.

**Closed by nwinter** 2016-05-22 19:38 UTC
