### ISSUE TITLE
Highlight arrow points to off-screen items in Inventory

### ISSUE THREAD

**Issue by Catsync** [codecombat/codecombat#2179] opened 2015-01-31 00:47 UTC
When a level requires an item and does the big highlight arrow, sometimes the item will initially be offscreen, so the arrow points at nothing (below the Play button).

**Comment by nwinter** [comment] 2015-02-27 19:17
We probably need to automatically scroll the inventory list to the item being pointed at before showing the arrow.

**Comment by nwinter** [comment] 2017-05-31 20:43
Fixed as duplicate of #3458

**Closed by nwinter** 2017-05-31 20:43 UTC
Labels: bug, good-for-newbies
