### ISSUE TITLE
Dynamic content, error 403

### ISSUE THREAD

**Issue by DocMoebius** [codecombat/codecombat#2163] opened 2015-01-28 10:55 UTC
Hi, on http://codecombat.com/i18n, i'm connected but i have an error 403 forbiden

![translate403](https://cloud.githubusercontent.com/assets/10712003/5936390/8608eea2-a6e4-11e4-9316-176b93295a3f.PNG)

**Comment by nwinter** [comment] 2015-01-28 17:02
Duplicate of #1866.

**Closed by nwinter** 2015-01-28 17:02 UTC
Labels: duplicate
