### ISSUE TITLE
Ladder game simulation crashes frequently

### ISSUE THREAD

**Issue by anter69** [codecombat/codecombat#3202] opened 2015-11-24 12:54 UTC
Ladder game simulation crashes frequently (every 20-30 minutes for me), which makes it hard to simulate a lot of games (and earn those extra gems).

Can something be done to prevent the crashes? Are these caused by bad code submitted? Can that even happen? Can those be detected and removed (automagically) somehow? Or could the page be set to reload every 10 minutes (or so)?

Config: win 7 + chrome 45, but it also happens on linux and firefox (all combinations) on 3 different computers.

Here are the console outputs of some crashed simulations (most recent first):

```
Finding game to simulate...
widgets.js:1 GET https://platform.twitter.com/js/button.c44c2dc193c555561d5830b3b543eb26.js net::ERR_BLOCKED_BY_CLIENTFunction.bind.test.window.__twttr.window.__twttr.widgets.window.__twttr.widgets.init.e.e @ widgets.js:1r @ widgets.js:9a @ widgets.js:8(anonymous function) @ widgets.js:8o @ widgets.js:8r._flush @ widgets.js:9t.exports @ widgets.js:8p @ widgets.js:8
dueling-grounds:1 Uncaught (in promise) undefined
dueling-grounds:1 Uncaught (in promise) undefined
CocoModel.coffee:95 Populated defaults for Level Zero Sum in 22ms
VM424:34 Generated random seed 3795144476 of type playerSession from sessionIDs ["550828a45106ef000de40cea", "55172d3a81389437054de9eb"] submissionCount 4
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 1043 ms
God.coffee:70 Venus: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Venus's Cheryl| Worker initialized after 1642ms
Angel.coffee:55 |Venus's Cheryl| Generated random seed 3795144476 of type playerSession from sessionIDs 550828a45106ef000de40cea,55172d3a81389437054de9eb submissionCount 0
```
(yes, I use uBlock)

```
Finding game to simulate...
VM10321:34 Generated random seed 811317832 of type playerSession from sessionIDs ["5551d928af92058705a85c18", "5568bf4225803b9805a04558"] submissionCount 3
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 406 ms
God.coffee:70 Angelos: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Angelos's Krieger| Generated random seed 811317832 of type playerSession from sessionIDs 5551d928af92058705a85c18,5568bf4225803b9805a04558 submissionCount 0
```

```
Finding game to simulate...
VM17652:34 Generated random seed 811317832 of type playerSession from sessionIDs ["5551d928af92058705a85c18", "5568bf4225803b9805a04558"] submissionCount 3
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 1092 ms
God.coffee:70 Týr: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Týr's Ray| Generated random seed 811317832 of type playerSession from sessionIDs 5551d928af92058705a85c18,5568bf4225803b9805a04558 submissionCount 0
```

```
Finding game to simulate...
VM6510:34 Generated random seed 8893472723 of type playerSession from sessionIDs ["55658eef5c27898a0511b775", "55aecd4bd3cfb0d61619ecbf"] submissionCount 11
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 712 ms
God.coffee:70 Apollo: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Apollo's Cheryl| Generated random seed 8893472723 of type playerSession from sessionIDs 55658eef5c27898a0511b775,55aecd4bd3cfb0d61619ecbf submissionCount 0
```

```
Finding game to simulate...
VM12505:34 Generated random seed 2089890667 of type playerSession from sessionIDs ["559f5b11ec5a698605d72201", "565453f7b39bfa88054ec2a0"] submissionCount 1
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 464 ms
God.coffee:70 Tyche: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Tyche's Archer| Generated random seed 2089890667 of type playerSession from sessionIDs 559f5b11ec5a698605d72201,565453f7b39bfa88054ec2a0 submissionCount 0
```

```
Finding game to simulate...
VM9188:34 Generated random seed 811317832 of type playerSession from sessionIDs ["5551d928af92058705a85c18", "5568bf4225803b9805a04558"] submissionCount 3
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 649 ms
God.coffee:70 Baldr: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Baldr's Pam| Generated random seed 811317832 of type playerSession from sessionIDs 5551d928af92058705a85c18,5568bf4225803b9805a04558 submissionCount 0
```

```
Finding game to simulate...
VM15952:34 Generated random seed 13844426802 of type playerSession from sessionIDs ["55172d3a81389437054de9eb", "565453f7b39bfa88054ec2a0"] submissionCount 1
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 726 ms
God.coffee:70 Hachiman: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Hachiman's Ray| Generated random seed 13844426802 of type playerSession from sessionIDs 55172d3a81389437054de9eb,565453f7b39bfa88054ec2a0 submissionCount 0
```

```
Finding game to simulate...
VM9304:34 Generated random seed 11052600307 of type playerSession from sessionIDs ["55172d3a81389437054de9eb", "55a9350b431ecfd016c25507"] submissionCount 4
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 629 ms
God.coffee:70 Inmar: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Inmar's Archer| Generated random seed 11052600307 of type playerSession from sessionIDs 55172d3a81389437054de9eb,55a9350b431ecfd016c25507 submissionCount 0
```

```
Finding game to simulate...
CocoModel.coffee:95 Populated defaults for Level Zero Sum in 26ms
Angel.coffee:55 |Tiamat's Ray| Worker initialized after 989ms
VM1951:34 Generated random seed 4496757831 of type playerSession from sessionIDs ["55172d3a81389437054de9eb", "554d35ac64f43b88056f1b95"] submissionCount 4
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 1623 ms
God.coffee:70 Tiamat: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Tiamat's Ray| Generated random seed 4496757831 of type playerSession from sessionIDs 55172d3a81389437054de9eb,554d35ac64f43b88056f1b95 submissionCount 0
```

```
Finding game to simulate...
VM5204:34 Generated random seed 5079033576 of type playerSession from sessionIDs ["550976d42e7f640f07bf7cbc", "55172d3a81389437054de9eb"] submissionCount 4
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 618 ms
God.coffee:70 Hyperion: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Hyperion's Krieger| Generated random seed 5079033576 of type playerSession from sessionIDs 550976d42e7f640f07bf7cbc,55172d3a81389437054de9eb submissionCount 0
```

```
Finding game to simulate...
VM2186:34 Generated random seed 9867670301 of type playerSession from sessionIDs ["5568bf4225803b9805a04558", "55a4e613431ecfd016bf1900"] submissionCount 1
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 1090 ms
God.coffee:70 Mitra: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Mitra's Cheryl| Generated random seed 9867670301 of type playerSession from sessionIDs 5568bf4225803b9805a04558,55a4e613431ecfd016bf1900 submissionCount 0
```

```
Finding game to simulate...
VM23223:34 Generated random seed 8917025934 of type playerSession from sessionIDs ["5568bf4225803b9805a04558", "560cdbdc01365b9a121848bb"] submissionCount 1
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 533 ms
God.coffee:70 Hunab Ku: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Hunab Ku's Cheryl| Generated random seed 8917025934 of type playerSession from sessionIDs 5568bf4225803b9805a04558,560cdbdc01365b9a121848bb submissionCount 0
```

```
Finding game to simulate...
CocoModel.coffee:95 Populated defaults for Level Dueling Grounds in 26ms
VM19597:34 Generated random seed 7579999683 of type playerSession from sessionIDs ["54f7dac4d1606ec105f3ff12", "55659fd705ed6a8b050999b5"] submissionCount 2
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 797 ms
God.coffee:70 Eos: Let there be light upon Dueling Grounds! (preload: undefined)
Angel.coffee:55 |Eos's Ray| Generated random seed 7579999683 of type playerSession from sessionIDs 54f7dac4d1606ec105f3ff12,55659fd705ed6a8b050999b5 submissionCount 0
```

```
Finding game to simulate...
CocoModel.coffee:95 Populated defaults for Level Zero Sum in 20ms
VM8124:34 Generated random seed 28016648899 of type playerSession from sessionIDs ["5518c2a0d69ccd3305a2cd93", "55f4640ea216618405debc2b"] submissionCount 1
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 695 ms
God.coffee:70 Ullr: Let there be light upon Zero Sum! (preload: undefined)
Angel.coffee:55 |Ullr's Cheryl| Generated random seed 28016648899 of type playerSession from sessionIDs 5518c2a0d69ccd3305a2cd93,55f4640ea216618405debc2b submissionCount 0
```

**Comment by Wutikorn** [comment] 2015-11-29 03:45
If u have a lot of RAM, use Microsoft Edge.  I found that it worked for an entire day and it didn't crashed itself on simulating.  After half an hour of simulating, it will use around 2-3GB of RAM.  It's slower than Chrome, but work all day which make it better than Chrome.  On the other hand, if u want to simulate for half an hour and make it fast, u should download Chrome 64Bit, which u have to select different platform when u download it.

**Comment by nwinter** [comment] 2015-11-30 02:01
Any better now with the latest update I added today?

**Comment by Wutikorn** [comment] 2015-11-30 03:56
Still have problem on Google Chrome, but not Microsoft Edge.  However, Microsoft Edge uses 2-4GB of RAM.  I think the simulating software has some problem of keep using too much memory then it crashes out.

**Comment by anter69** [comment] 2015-11-30 09:04
> Any better now with the latest update I added today?

First crash after about 20 minutes. (win7, chrome 45 64bit, 8gb ram)

```
Generated random seed -8839382803 of type playerSession from sessionIDs ["55ef35a10746491310f938aa", "55fa370575328a840569ffa3"] submissionCount 0
LevelLoader.coffee:416 World has been initialized from level loader.
LevelLoader.coffee:311 SuperModel for Level loaded in 955 ms
God.coffee:72 Umvelinqangi: Let there be light upon Ace of Coders! (preload: undefined)
Angel.coffee:56 |Umvelinqangi's Archer| Generated random seed -8839382803 of type playerSession from sessionIDs 55ef35a10746491310f938aa,55fa370575328a840569ffa3 submissionCount 0
```

**Comment by nwinter** [comment] 2015-11-30 15:22
That's weird, I looked up one of the games:

http://codecombat.com/play/spectate/zero-sum?session-one=5551d928af92058705a85c18&session-two=5517bbbf5afdf532055761e1

It happened to be a match between you and Andre95, which ended quickly with no memory buildup. Seems weird that would be one that would crash it.

I need to investigate more...

**Comment by Wutikorn** [comment] 2015-11-30 22:15
When will I get gems by the way?  How long I have to wait after I simulated games until I receive my gems?

**Comment by nwinter** [comment] 2015-11-30 22:19
Twiddle the volume button a bunch of times for now. More info in [this thread](http://discourse.codecombat.com/t/need-better-gear-earn-gems-for-simulating-games/2769/35).

**Comment by anter69** [comment] 2015-12-01 08:14
> That's weird, I looked up one of the games:

> http://codecombat.com/play/spectate/zero-sum?session-one=5551d928af92058705a85c18&session-two=5517bbbf5afdf532055761e1

> It happened to be a match between you and Andre95, which ended quickly with no memory buildup. Seems weird that would be one that would crash it.

> I need to investigate more...

Well, I clicked on the replay: the level loaded (I see the battlefield with the two heros), but then memory and cpu usage went through the roof - my pc* basically went to a freeze for about 5 minutes, then finally the tab crashed and I got the controls back...

* pc: 4-core i3-3220 desktop, 8gb ram, windows 7, chrome 45 64bit

**Comment by nwinter** [comment] 2015-12-01 13:43
Does running your own strategy during normal play on Zero Sum and Ace of Coders take a lot of CPU/memory? I wonder if you are seeing a lot of crashes because you simulate a lot of your own games as part of simulating for your courses/clans, and your own games are particularly crashworthy on Chrome right now.

**Comment by anter69** [comment] 2015-12-02 08:26
> Does running your own strategy during normal play on Zero Sum and Ace of Coders take a lot of CPU/memory?

No, it's about 15 lines of code, along the very simple strategy of *collect coins - summon friends - command friends to attack*.

Although I do run a value/distance calculation for coins, which might make it a bit heavier (especially when there is a big bunch of coins...)

**Comment by anter69** [comment] 2015-12-04 11:11
Issue may be related to #3212?

**Comment by anter69** [comment] 2015-12-07 10:48
This morning I see a great improvement (I didn't check during the weekdend):
* the simulations are running since 1.5 hours without crashes
* the memory usage stays reasonable (~400MB)

**Comment by Wutikorn** [comment] 2015-12-17 16:17
How many cores of CPU can a single simulator use?

**Comment by nwinter** [comment] 2015-12-17 16:18
Should be one core, so you can open one tab per core that you want to use.

**Comment by Wutikorn** [comment] 2015-12-17 16:25
Was there a connection problem with the server just several hours ago?  All my PCs from different places stuck and wouldn't continue until I refresh it.  It said like Result is being sent to sever(for several hours).  Is it possible to make the simulator refresh itself after it stuck at same process for several minutes?

**Comment by nwinter** [comment] 2016-05-22 20:17
Closing based on anter69's last comment; can reopen if it gets bad again.

**Closed by nwinter** 2016-05-22 20:17 UTC

**Comment by JasonLin5-code** [comment] 2022-09-10 12:19
@nwinter I simulated about 800000 games, but i just have 63000 now. Is this a bug?

**Comment by nwinter** [comment] 2022-09-25 21:58
@JasonLin5-code Possibly–I haven't seen any issues with simulation counts being off. Sometimes I switch accounts and am surprised to see a lower count on the other account before I realize that I've switched, but that's about it. Let me know if you can reproduce issues with resetting/decreasing simulation counts.

**Comment by JasonLin5-code** [comment] 2022-09-26 00:50
Hi, @nwinter , if you can't add me simulations, that's ok, but as you see:
![image](https://user-images.githubusercontent.com/113188575/192173648-85422ce0-6e6a-4053-936a-13feddc54076.png)
I got 119,960 simulations, but:
![image](https://user-images.githubusercontent.com/113188575/192173875-e3f42944-0077-4b87-8f95-0f99172ba596.png)
It just gave me 42954 simulation gems and XP
can you help me get the gems i should get? Thanks!

**Comment by JasonLin5-code** [comment] 2022-10-03 07:27
@nwinter I lost about 37000 simulation now, every time the page refreshes, my simulation just become lower. I need help, thanks
