### ISSUE TITLE
Objects arguments are passed by copy and not reference

### ISSUE THREAD

**Issue by AdrianCgw** [codecombat/codecombat#3372] opened 2016-02-01 08:33 UTC
In CodeCombat, JavaScript,  the object assignment is done by reference. 
But the object argument passing is done by copy.

See the following code:
```
var outsidePos={x:1,y:1};
function modifyPos(mypos){
    mypos.x=5;
}

modifyPos(outsidePos);
this.say("still "+ outsidePos.x);
anotherPos=outsidePos;
anotherPos.x=5;
this.say("and now "+ outsidePos.x);

this.move({x:this.pos.x+10,y:this.pos.y});
var old_pos=this.pos;
this.say(old_pos);
this.say(old_pos);
```

What should be the expected behavior?

The reference vs copy behavior can be quite a shock for a beginner, it should be properly documented  by game levels.

**Comment by AdrianCgw** [comment] 2016-02-01 08:51
Tested in:
https://codecombat.com/play/level/forest-flower-grove
Same behavior in Python:

```
outside=(1,1)

def modifyPos(mypos):
    self.say("here "+mypos[0])
    mypos[0]=5

modifyPos(outside)
self.say("still "+outside[0])

anotherPos=outside
anotherPos[0]=5
self.say("and now "+outside[0])
```

And apparently Python is pass object references by value while will probably make young students questions their career choices :)
http://robertheaton.com/2014/02/09/pythons-pass-by-object-reference-as-explained-by-philip-k-dick/

**Comment by nwinter** [comment] 2016-02-01 14:48
I think the issue is that our API protection is insufficiently smart at the moment. It sees you modifying a variable passed into a function and thinks, oh no, you are trying to hack a variable that doesn't belong to you, let's not persist that change outside of the function! But it doesn't know that this is your variable that you declared and your function and you should be able to do whatever you want with it.

We will have some improvements for this behavior when the new interpreter that Rob is working on is done.

**Comment by nwinter** [comment] 2016-05-22 21:06
Should be fixed with @basicer's new Esper interpreter.

**Closed by nwinter** 2016-05-22 21:06 UTC
