### ISSUE TITLE
Upgrading Brunch to v2

### ISSUE THREAD

**Issue by paulmillr** [codecombat/codecombat#3518] opened 2016-03-31 00:34 UTC
Hello!

We have made a lot of under-the-hood improvements in Brunch v2. Specifically, NPM support is a big one. We'd like to help you with upgrading to the version; while also looking into possible ways of incorporating new features based on the upgrade feedback & current use cases.

Would you be open to that?

**Comment by sderickson** [comment] 2016-03-31 16:28
Absolutely, thanks! What's the upgrade process look like? [Last time I upgraded](921054d53f6f454b77859cfeb48f74d6b66b1f12) it was basically just a matter of upgrading versions.

**Comment by paulmillr** [comment] 2016-03-31 19:13
We'll drop Bower. `bower.json` deps are going to be put inside `package.json` and become node modules. That's mostly it. The reason for that is — the node community decided it's not worth to support bower and many third-party deps are getting rid of it.

**Comment by nwinter** [comment] 2016-04-16 23:38
Not sure how using `package.json` for Bower dependencies would work; is that typically a big change, since many client-side packages in Bower might not be in NPM?

**Comment by paulmillr** [comment] 2016-04-17 16:51
NPM allows to use GitHub repos. Bower is simply a mapping of "alias-to-gh-repo". So, totally doable.

**Comment by sderickson** [comment] 2016-04-25 21:45
I played around with brunch v2 this weekend, and I had a couple questions:

1. How would we swap `lodash` for `underscore` in Backbone on the client side?
1. When I `require('bootstrap')`, it complains that `jQuery` is not defined (from [`transition.js`](https://github.com/twbs/bootstrap/blob/10606a73bcbfc6c723d60e2a1069c921afff0d2a/js/transition.js#L59) if I remember correctly), and I had to [set it to `window` to make it work](https://github.com/sderickson/home/blob/master/app/Application.coffee#L1). Is there another solution?

**Comment by paulmillr** [comment] 2016-04-25 23:17
@goshakkk

**Comment by goshakkk** [comment] 2016-04-26 05:54
1. it probably will be possible to do that by a) adding `lodash` to your package.json, b) changing the config so that `lodash` is aliased as `underscore` (though they might still collide, and if that doesn't work, gives us a ping and we'll fix that)

```javascript
module.exports = {
  npm: {
    aliases: {
      underscore: 'lodash'
    }
  }
}
```

2. seems like the `bootstrap` package does depend on the global. One way to remove that from *your* code is to have brunch expose it as a global for you

```javascript
module.exports = {
  // ...
  npm: {
    globals: {
      jQuery: 'jquery'
    }
  }
}
```

**Comment by sderickson** [comment] 2016-04-27 17:20
@goshakkk Thanks for the tips, will try them out!

**Comment by duybkict** [comment] 2016-05-19 10:43
I tried to upgrade brunch and related packages to v2 but running `brunch build --env fast` takes too long... Maybe it hanged somewhere along the road

**Comment by goshakkk** [comment] 2016-05-19 10:44
@duybkict sorry to hear that is happening... is there a branch or something that we can see and debug locally?

**Comment by duybkict** [comment] 2016-05-19 15:41
Here í my working branch on my repo
https://github.com/duybkict/codecombat/tree/vagrant-brunch-v2
you could give it a try, `brunch build` stucked at installing npm packages

**Comment by goshakkk** [comment] 2016-05-21 08:24
I just checked it out — looks like it's caused by the postinstall hook which runs brunch, which tries to update packages with npm, which runs another brunch... and so on. The solution for this would be to remove the brunch call from the postinstall hook.

After that, I've seen a few errors:

```
21 May 08:08:47 - error: Resolving deps of app/views/editor/DeltaView.coffee failed. Could not load module 'vendor/diffview' from '/Users/goshakkk/Projects/oss/codecombat-upgrade/app/views/editor'. Possible solution: add 'vendor' to package.json and `npm install`.
21 May 08:08:47 - error: Resolving deps of app/views/ladder/LadderTabView.coffee failed. Could not load module 'vendor/d3' from '/Users/goshakkk/Projects/oss/codecombat-upgrade/app/views/ladder'. Possible solution: add 'vendor' to package.json and `npm install`.
```

which looks like it's caused by trying to `require` something from `vendor` (but vendor isn't wrapped into modules and therefore brunch fails to resolve these requires).

Looking a bit further, it looks like `treema` is a bower package — meaning it is going to be included as-is and you probably shouldn't require it (unless I'm missing something)

With Brunch 2 moving to npm as the primary package manager, you will easily find that most, if not all, of your bower dependencies are also present on npm — to use these, then, you will have to add them to your `package.json` and call `var dep = require('dep-name')` in your code to use it.

If you want me to, I can further dig into this to facilitate the transition; or you can ping me there if you'd like to continue this yourself and run into something.

**Comment by duybkict** [comment] 2016-05-21 15:03
This sure is a big transition, I am not sure if CodeCombat is ready for it yet
Lets ask @sderickson @nwinter

**Comment by goshakkk** [comment] 2016-05-21 16:02
Fwiw, bower & pre-2 behavior (e.g. no `require` processing) can be had with Brunch 2, too. Just add

```javascript
  npm: { enabled: false }
```
to the config. Should be ok as the first step.

**Comment by nwinter** [comment] 2018-01-25 20:48
(We moved to Webpack eventually)

**Closed by nwinter** 2018-01-25 20:48 UTC
