### ISSUE TITLE
Infinite loop loading Sarven Shepherd "Programming mistake finding a build type!"

### ISSUE THREAD

**Issue by skookumgh** [codecombat/codecombat#6043] opened 2020-11-09 11:03 UTC
Sarven Shepherd won't load (even first time) for me and infinite loop detected.
Logged in: YES
Browser: Chrome Version 86.0.4240.111 (Official Build) (x86_64)
OS: macOS Catalina 10.15.7
Dev Console:
-------
Anubis's Cyril| Assigned power 65 to wave wave3 with difficulty 0
aether-app-59b52c79a8e22f39b229.bundle.js:123 |Anubis's Cyril| Assigned power 3500 to wave yak0 with difficulty 0
aether-app-59b52c79a8e22f39b229.bundle.js:123 |Anubis's Cyril| Assigned power 3500 to wave yak1 with difficulty 0
aether_worker.js:9 Modern javascript detected, aw yeah!
2aether-app-59b52c79a8e22f39b229.bundle.js:123 |Anubis's Cyril| Programming mistake finding a build type! NaN 2 [object Object],[object Object]
aether_worker.js:26 Using modern language plugin: python
app.js:38 Saw view load event #infinite-loop-modal #infinite-loop-modal
aether-app-59b52c79a8e22f39b229.bundle.js:123 |Anubis's Cyril| Modern javascript detected, aw yeah!

**Comment by nwinter** [comment] 2020-11-27 14:51
This might be a rare bug on certain random seeds? I can't reproduce or figure out why the error is happening. What's your CodeCombat username?

**Comment by skookumgh** [comment] 2020-12-01 12:51
cloneclon

**Comment by nwinter** [comment] 2020-12-08 23:19
I see the issue, thanks! Fixed now.

**Closed by nwinter** 2020-12-08 23:19 UTC
Labels: bug

**Comment by skookumgh** [comment] 2020-12-11 01:28
Good job, Nick!
