### ISSUE TITLE
Chrome crashes when spectating certain games

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3212] opened 2015-11-29 02:02 UTC
I can consistently reproduce an extreme slowdown followed by a browser crash soon after starting to spectate this [Ace of Coders match](http://codecombat.com/play/spectate/ace-of-coders?session-one=55fa016d75328a840569d5d8&session-two=55e1d23686c019bc47b640fe), running in Chrome 46.0.2490.86m on Windows 10.

This is not reproducible on Firefox, nor in other matches of the same arena in Chrome, so it may be a very specific bug.

I have not tested it in other machines yet, so please [spectate this match](http://codecombat.com/play/spectate/ace-of-coders?session-one=55fa016d75328a840569d5d8&session-two=55e1d23686c019bc47b640fe) on Chrome to check whether the issue is reproducible.

**Comment by popey456963** [comment] 2015-12-04 09:59
I can confirm this on Chrome 47.0.2526.73m on Windows 7.  This appears to be caused by some sort of infinite loop problem or unoptimised code, as my CPU maxes at 100% before eventually crashing.  Memory stays normal throughout the entire thing.

**Comment by anter69** [comment] 2015-12-04 11:11
Issue may be related to #3202?

**Comment by Wutikorn** [comment] 2015-12-17 16:18
What CPU do you have?  Is there still a problem?  Try Firefox nightly if you want

**Comment by UltCombo** [comment] 2015-12-17 16:37
@Wutikorn The issue is not reproducible on Firefox, as already mentioned in the original bug report above.

The bug is reproducible on different machines, on different versions of Windows and different versions of Chrome, so I don't think the CPU plays a big role here.

I've also just reproduced the issue in OSX Yosemite (10.10.5) running Chrome 47.0.2526.106 (64-bit).

**Comment by UltCombo** [comment] 2015-12-17 16:40
Beware: while in Windows it only crashed the given Chrome tab, in OS X the whole OS froze and I had to hard reset.

**Comment by popey456963** [comment] 2015-12-17 23:14
I have an Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz at the moment.  Although it seems to not matter what CPU the simulation is run on because I've also crashed it with an AMD processor.

**Comment by nwinter** [comment] 2016-05-22 20:42
Should be fixed with @basicer's new Esper interpreter. Note our test game is no longer a good test case because the code doesn't run (probably because Esper makes us now in strict mode and so there is an error at the beginning).

**Closed by nwinter** 2016-05-22 20:42 UTC
Labels: browser-compat, bug
