### ISSUE TITLE
Cleanup sass files

### ISSUE THREAD

**Issue by Imperadeiro98** [codecombat/codecombat#3158] opened 2015-11-06 14:52 UTC
There are a few files that have unused properties in them.

Example: 
- [x] https://github.com/codecombat/codecombat/blob/master/app/styles/achievements.sass
- [x] https://github.com/codecombat/codecombat/blob/master/app/styles/blog.sass (is it used?)
- [x] https://github.com/codecombat/codecombat/blob/master/app/styles/contact.sass (is it used?)

**Comment by duybkict** [comment] 2016-05-11 10:12
I found out that blog.sass and contact.asas are not used anywhere.
achievements.sass is used by AchievementPopup, however, it is not used anywhere, I think these files should be dropped, too. Please correct me if I am wrong @Imperadeiro98

**Comment by Imperadeiro98** [comment] 2016-05-11 14:16
The problem with achievements.sass is that it has some styles that are not used. Other styles, for example the ones related to AchievementPopup, are still used, so the work here would be to go though  the file and check what is being used.

**Comment by sderickson** [comment] 2016-05-11 16:59
Merged in 8328d955a8b982b9dc50d8c0000df9f730fe2452, but leaving this issue open since as @Imperadeiro98 pointed out, there's more work to be done!

**Comment by duybkict** [comment] 2016-05-12 02:03
Where is AchievementPopup being used? I'm trying to find out but haven't figured it out yet

**Comment by sderickson** [comment] 2016-05-12 16:07
https://github.com/codecombat/codecombat/blob/master/app/views/core/RootView.coffee#L41-L47

**Comment by duybkict** [comment] 2016-05-13 06:52
This popup is really hard to test, do you have any suggestion on how i can show this popup without actually get an achievement?

**Comment by sderickson** [comment] 2016-05-13 18:47
The achievement editor displays an example. You'd need to be on your dev environment and on an 'admin' user, then navigate to `/editor/achievement` and select any achievement there.

You can also create a test which constructs the view and gives it to `jasmine.demoEl`. Here's an example of how to test and demo a view:

https://github.com/codecombat/codecombat/blob/3ad395ecb80ce56757f1605d00aed1c1cafcfbaf/test/app/views/account/PaymentsView.spec.coffee

You can see the demo by going here:

http://localhost:3000/test/views/account/PaymentsView.spec

And clicking 'Show Demos'. I recommend writing tests and setting them up to demo in general, and especially in cases like this where states are hard to reproduce on demand.

**Comment by sderickson** [comment] 2016-05-17 16:41
Closing this now that achievements.sass is cleaned up.

https://github.com/codecombat/codecombat/pull/3649

If more files are found that need cleaning, please open more issues specifically for them, thanks!

**Closed by sderickson** 2016-05-17 16:41 UTC
Labels: good-for-newbies
